baseURL: "https://pragathip.github.io/" 
title: Pragathi Praveena
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

params:
    author: Pragathi Praveena
    googleAnalyticsID: "G-EN8CHN2R1H"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pragathi Praveena
          subtitle: "👋🏼 I am interested in **human-robot interaction** and **collaborative systems**. I am a Postdoctoral Fellow at the [Robotics Institute, Carnegie Mellon University](https://www.ri.cmu.edu/) where I contribute to the [NSF AI-CARING Institute.](https://www.ai-caring.org/) 
          I have a Ph.D. in [Computer Science](https://www.cs.wisc.edu/) from the [University
of Wisconsin-Madison,](https://www.wisc.edu/) where I was part of the [People and Robots Lab.](https://peopleandrobots.wisc.edu/)
<br><br> My research explores the intersection of HRI and CSCW, with a focus on developing novel interactive systems that facilitate human-to-human communication and collaboration. My dissertation work was on [**Robotic Groupware**.](https://www.proquest.com/dissertations-theses/towards-effective-robotic-groupware/docview/2937238328/se-2) 
My favorite paper from my Ph.D. journey is on the [*Periscope* robotic camera system](https://dl.acm.org/doi/10.1145/3610199) (see [1-minute teaser](https://twitter.com/HRIPioneers/status/1626663545810354176?s=20)🎉), 
which facilitates remote collaboration on physical tasks between two people. My second favorite paper explored the use of [collaborative robot arms in cinematography.](https://dl.acm.org/doi/10.1145/3544549.3585715)
<br><br>
Prior to joining graduate school, I was a junior research scientist for two years at [Xerox Research Center India](https://www.news.conduent.com/news/Xerox-expands-healthcare-research-at-hospitals-with-remote-sensing) 
where I built algorithms for monitoring a person’s breathing using webcams [(see video).](https://youtu.be/a7BPu4mUKaY)
I have a B.Tech. in Electrical Engineering from the [Indian Institute of Technology Madras.](https://www.iitm.ac.in/)
<br>
<blockquote>I will be presenting at the [Talking Robotics](https://www.youtube.com/@talkingrobotics2699) online seminar series on Wednesday, October 16th at 12 PM ET. Find details about my talk [here,](https://talking-robotics.github.io/upcoming/pragathi_praveena/) and register using [this link.](https://us02web.zoom.us/meeting/register/tZYpcu-uqj8sEtdp5z2tPyjrLdhBxNQgp31r#/registration)</blockquote>"
          imageUrl: "/picture.jpeg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Pragathi Praveena
    socialIcons:
        - name: CV
          url: /praveena-cv.pdf
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=1VSKpsIAAAAJ&view_op=list_works&sortby=pubdate
        - name: Email
          url: mailto:pragathi@cmu.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/itispragathi/
        - name: Twitter
          url: https://twitter.com/itispragathi

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Pragathi Praveena"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
